upstream frontend {
    server client:3000;
}

upstream students_api {
    server api_golang_studentservice:5001;
}

upstream teachers_api {
    server api_java_teacherservice:5002;
}

upstream employees_api {
    server api_python_employeeservice:5003;
}

server {
    listen 80;

    location / {
        proxy_pass http://frontend;
    }

    location /students {
        proxy_pass http://students_api;
    }

    location /teachers {
        proxy_pass http://teachers_api;
    }

    location /employees {
        proxy_pass http://employees_api;
    }
}